
[[redirects]]
  from = "https://hopeful-noether-2a22a6.netlify.app/editor.html"
  to = "https://revpower-demo.netlify.app/index.html"
  status = 404

[[headers]]
for = "/*"

[headers.values]
Permissions-Policy = "camera=(), microphone=()"
