
[[redirects]]
  from = "https://dev.demostats.tools/editor/*"
  to = "https://rev.demostats.tools:splat"
  status = 301

[[headers]]
for = "/*"

[headers.values]
Permissions-Policy = "camera=(), microphone=()"
