
[[redirects]]
from = "/some-test123.netlify.app/*"
to = "https://pensive-yalow-cd22c7.netlify.app:splat"
status = 200
force = false

[[headers]]
for = "/*"

[headers.values]
Permissions-Policy = "camera=(), microphone=()"
