
[[redirects]]
  from = "https://dev.demostats.tools/*"
  to = "https://rev.demostats.tools:splat"
  status = 200
  force = false

[[headers]]
for = "/*"

[headers.values]
Permissions-Policy = "camera=(), microphone=()"
