
[[redirects]]
from = "/editor"
to = "https://rev-demo.netlify.app/.netlify/functions/testing"
status = 200




[[headers]]
for = "/*"

[headers.values]
Permissions-Policy = "camera=(), microphone=()"
